$('.owl-carousel').owlCarousel({
    loop:true,
    autoplay:true,
    margin:30,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        1000:{
            items:3
        }
    }
})